include ':src:multisrc:madara'

// English
include ':src:english:asurascans'
include ':src:english:reaperscans'
include ':src:english:flamescans'
include ':src:english:mangakakalot'
include ':src:english:mangabats'
include ':src:english:mangaread'
include ':src:english:xbato'
include ':src:english:comick'
include ':src:english:mangadex'
include ':src:english:mangasee'
include ':src:english:mangapark'
include ':src:english:mangahere'
include ':src:english:fanfox'
include ':src:english:manganato'
include ':src:english:readm'
include ':src:english:luminousscans'
include ':src:english:alphascans'
include ':src:english:zeroscans'
include ':src:english:mangahub'
include ':src:english:manhwatop'
include ':src:english:manhwaclan'
include ':src:english:zinmanga'
include ':src:english:isekaiscan'
include ':src:english:manhuaplus'
include ':src:english:tcbscans'
include ':src:english:nightscans'
include ':src:english:voidscans'
include ':src:english:mangabuddy'
include ':src:english:toonily'
include ':src:english:mmscans'
include ':src:english:mangalife'
include ':src:english:mangapill'
include ':src:english:mangafreak'
include ':src:english:readmanhwa'
include ':src:english:mangaowl'
include ':src:english:mangainn'
include ':src:english:mangago'
include ':src:english:comicextra'
include ':src:english:mangastream'
include ':src:english:manhwa18'
include ':src:english:hatigarmscans'
include ':src:english:drakeina'
include ':src:english:mangatown'
include ':src:english:gigascans'
include ':src:english:suryascans'
include ':src:english:mangahere'
include ':src:english:nettruyen'

// Arabic
include ':src:arabic:azoramoon'
include ':src:arabic:mangaswat'
include ':src:arabic:mangalek'
include ':src:arabic:manga3asq'
include ':src:arabic:aresmanga'
include ':src:arabic:gmanga'
include ':src:arabic:mangaarab'
include ':src:arabic:arabianscan'
include ':src:arabic:teamx'
include ':src:arabic:galaxymanga'
include ':src:arabic:mangagtr'
include ':src:arabic:hizomanga'
include ':src:arabic:ozulscans'
include ':src:arabic:phenixscans'
include ':src:arabic:tajmanga'
include ':src:arabic:mangajy'
include ':src:arabic:scan4arab'
include ':src:arabic:toonsgate'
include ':src:arabic:mangamasr'
include ':src:arabic:mangaor'
include ':src:arabic:alwatanmanga'
include ':src:arabic:mangasky'
include ':src:arabic:mangaflame'
include ':src:arabic:starmanga'
include ':src:arabic:konoha'
include ':src:arabic:hamlamanga'
include ':src:arabic:mangasnow'
include ':src:arabic:mangatak'
include ':src:arabic:elarabscans'
include ':src:arabic:donghuaar'
include ':src:arabic:mangaholics'
include ':src:arabic:arabseed'
include ':src:arabic:mangaink_ar'
