apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion rootProject.ext.compileSdk
    namespace 'eu.kanade.tachiyomi.multisrc.madara'

    defaultConfig {
        minSdkVersion rootProject.ext.minSdk
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
        }
    }
}

dependencies {
    compileOnly "com.github.keiyoushi:extensions-lib:v1.4.2.1"
    compileOnly 'com.squareup.okhttp3:okhttp:4.12.0'
    compileOnly 'org.jsoup:jsoup:1.17.2'
}
