apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion rootProject.ext.compileSdk
    defaultConfig { minSdkVersion rootProject.ext.minSdk }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
    sourceSets { main { java.srcDirs = ['src'] } }
}

dependencies {
    compileOnly "com.github.mihonapp.extensions-lib:extensions-lib:${rootProject.ext.extLibVersion}.${rootProject.ext.extLibRevision}"
    compileOnly 'com.squareup.okhttp3:okhttp:4.12.0'
    compileOnly 'org.jsoup:jsoup:1.17.2'
}
